---

apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "accident"
  labels: 
    app: "accident"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "556"
spec: 
  selector: 
    matchLabels: 
      app: "accident"
  replicas: 3
  template: 
    metadata: 
      labels: 
        app: "accident"
    spec: 
      containers: 
        - 
          name: "accident"
          image: "ghcr.io/shinseongjin2/industrialaccident_v1/accident:v3.0"
          ports: 
            - 
              containerPort: 8080
          readinessProbe: 
            httpGet: 
              path: "/some/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe: 
            httpGet: 
              path: "/some/health"
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
---

apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "assessment"
  labels: 
    app: "assessment"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "556"
spec: 
  selector: 
    matchLabels: 
      app: "assessment"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "assessment"
    spec: 
      containers: 
        - 
          name: "assessment"
          image: "ghcr.io/shinseongjin2/industrialaccident_v1/assessment:v3.0"
          ports: 
            - 
              containerPort: 8080
          readinessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
---

apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "compensation"
  labels: 
    app: "compensation"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "556"
spec: 
  selector: 
    matchLabels: 
      app: "compensation"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "compensation"
    spec: 
      containers: 
        - 
          name: "compensation"
          image: "ghcr.io/shinseongjin2/industrialaccident_v1/compensation:v3.0"
          ports: 
            - 
              containerPort: 8080
          readinessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
---

apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "statistics"
  labels: 
    app: "statistics"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "556"
spec: 
  selector: 
    matchLabels: 
      app: "statistics"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "statistics"
    spec: 
      containers: 
        - 
          name: "statistics"
          image: "ghcr.io/shinseongjin2/industrialaccident_v1/statistics:v3.0"
          ports: 
            - 
              containerPort: 8080
          readinessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
---

apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "notification"
  labels: 
    app: "notification"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "556"
spec: 
  selector: 
    matchLabels: 
      app: "notification"
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: "notification"
    spec: 
      containers: 
        - 
          name: "notification"
          image: "ghcr.io/shinseongjin2/industrialaccident_v1/notification:v3.0"
          ports: 
            - 
              containerPort: 8080
          readinessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe: 
            httpGet: 
              path: "/actuator/health"
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
---

apiVersion: "v1"
kind: "Service"
metadata: 
  name: "accident"
  labels: 
    app: "accident"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "356"
spec: 
  ports: 
    - 
      port: 8080
      targetPort: 8080
  selector: 
    app: "accident"

---

apiVersion: "v1"
kind: "Service"
metadata: 
  name: "assessment"
  labels: 
    app: "assessment"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "356"
spec: 
  ports: 
    - 
      port: 8080
      targetPort: 8080
  selector: 
    app: "assessment"

---

apiVersion: "v1"
kind: "Service"
metadata: 
  name: "compensation"
  labels: 
    app: "compensation"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "356"
spec: 
  ports: 
    - 
      port: 8080
      targetPort: 8080
  selector: 
    app: "compensation"

---

apiVersion: "v1"
kind: "Service"
metadata: 
  name: "statistics"
  labels: 
    app: "statistics"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "356"
spec: 
  ports: 
    - 
      port: 8080
      targetPort: 8080
  selector: 
    app: "statistics"

---

apiVersion: "v1"
kind: "Service"
metadata: 
  name: "notification"
  labels: 
    app: "notification"
  namespace: ""
  annotations: 
    msaez.io/x: "775"
    msaez.io/y: "356"
spec: 
  ports: 
    - 
      port: 8080
      targetPort: 8080
  selector: 
    app: "notification"

---

apiVersion: "autoscaling/v2beta2"
kind: "HorizontalPodAutoscaler"
metadata: 
  name: "accident"
spec: 
  scaleTargetRef: {}
  minReplicas: 1
  maxReplicas: 10
  metrics: 
    - 
      type: "Resource"
      resource: 
        name: "cpu"
        targetAverageUtilization: 50

